from __future__ import annotations

from collections import defaultdict
from functools import lru_cache
from pathlib import Path
from typing import Any

import numpy as np
import torch
from torch.utils.data import Dataset

from ocrap.data.serialization import load_npz_selected
from ocrap.models.data import (
    MODEL_SAMPLE_NPZ_KEYS,
    iter_sample_paths_many,
    manifest_metadata_for_path,
    sample_to_feature,
    samples_to_feature_matrix,
    scalar_metadata_for_path,
)


# The external-baseline adapters intentionally derive all supervision from the
# current OC-RAP sample files.  No OC-RAP model predictions or calibration labels
# are used as inputs to GameFormer/BeTop policies.
ACTOR_TOPO_FEATURE_DIM = 16
MAP_TOPO_FEATURE_DIM = 14
GAMEFORMER_STATE_DIM = 9
SOURCE_AGENT_STATE_DIM = 9  # x,y,vx,vy,heading,length,width,type,valid
SOURCE_CURRENT_STATE_DIM = 6  # x,y,heading,speed,longitudinal_accel,steering
SOURCE_MAP_POINT_DIM = 6  # rel_x,rel_y,dx,dy,cos(theta),sin(theta)
SOURCE_MAP_META_DIM = 4  # kind,on_route,traffic_control,speed_limit
SOURCE_MAP_CENTER_DIM = 3  # x,y,heading

# Read only arrays that external planners actually consume.  OC-RAP NPZs can
# contain large teacher-future/debug tensors; decompressing those for imitation
# planners is pure I/O overhead and was particularly expensive for near/contact
# datasets with 11/13 future branches per sample.
EXTERNAL_BASELINE_NPZ_KEYS: frozenset[str] = MODEL_SAMPLE_NPZ_KEYS | frozenset({
    "dt", "oracle_gap_star", "post_contact_deployability",
    "prefix_macro_name", "yaw_rate", "yaw_rate_series", "initial_speed", "regime_label",
})


def load_external_sample(path: str | Path) -> dict[str, Any]:
    return load_npz_selected(path, EXTERNAL_BASELINE_NPZ_KEYS)


def use_teacher_branch_context(cfg: dict[str, Any]) -> bool:
    """Return whether a learned baseline may consume teacher-only root tensors.

    ``m_star``/root signatures/root probabilities are generated by the OC-RAP
    teacher and are unavailable to a deployable feature-only closed-loop policy.
    Teacher branch context is disabled by default.  It may only be enabled for an
    explicitly named oracle diagnostic; paper baselines must use observable inputs.
    """
    bcfg = cfg.get("external_baselines", {}) if isinstance(cfg.get("external_baselines", {}), dict) else {}
    mcfg = bcfg.get("model", {}) if isinstance(bcfg.get("model", {}), dict) else {}
    return bool(mcfg.get("use_teacher_branch_context", False))


def _scalar(d: dict[str, Any], key: str, default: float = 0.0) -> float:
    try:
        return float(np.asarray(d.get(key, default)).item())
    except Exception:
        return float(default)


def _int(d: dict[str, Any], key: str, default: int = 0) -> int:
    try:
        return int(np.asarray(d.get(key, default)).item())
    except Exception:
        return int(default)


def _str(d: dict[str, Any], key: str, default: str = "") -> str:
    try:
        v = np.asarray(d.get(key, default)).item()
        if isinstance(v, bytes):
            return v.decode("utf-8", errors="ignore")
        return str(v)
    except Exception:
        return str(default)


def _cfg_int(cfg: dict[str, Any], path: tuple[str, ...], default: int) -> int:
    cur: Any = cfg
    for key in path:
        if not isinstance(cur, dict) or key not in cur:
            return int(default)
        cur = cur[key]
    try:
        return int(cur)
    except Exception:
        return int(default)


def _cfg_float(cfg: dict[str, Any], path: tuple[str, ...], default: float) -> float:
    cur: Any = cfg
    for key in path:
        if not isinstance(cur, dict) or key not in cur:
            return float(default)
        cur = cur[key]
    try:
        return float(cur)
    except Exception:
        return float(default)


def _pad_1d(x: Any, n: int, *, fill: float = 0.0, dtype=np.float32) -> np.ndarray:
    out = np.full((int(n),), fill, dtype=dtype)
    if n <= 0:
        return out
    v = np.asarray(x, dtype=dtype).reshape(-1)
    m = min(int(n), int(v.size))
    if m > 0:
        out[:m] = v[:m]
    return np.nan_to_num(out, nan=fill, posinf=fill, neginf=fill)


def _pad_bool_1d(x: Any, n: int, *, fill: bool = False) -> np.ndarray:
    out = np.full((int(n),), bool(fill), dtype=bool)
    if n <= 0:
        return out
    v = np.asarray(x).reshape(-1).astype(bool)
    m = min(int(n), int(v.size))
    if m > 0:
        out[:m] = v[:m]
    return out


def _pad_2d(x: Any, shape: tuple[int, int], *, fill: float = 0.0, dtype=np.float32) -> np.ndarray:
    r, c = int(shape[0]), int(shape[1])
    out = np.full((r, c), fill, dtype=dtype)
    if r <= 0 or c <= 0:
        return out
    v = np.asarray(x, dtype=dtype)
    if v.ndim == 1:
        v = v.reshape(1, -1)
    if v.ndim != 2:
        return out
    rr, cc = min(r, v.shape[0]), min(c, v.shape[1])
    if rr > 0 and cc > 0:
        out[:rr, :cc] = v[:rr, :cc]
    return np.nan_to_num(out, nan=fill, posinf=fill, neginf=fill)


def _pad_3d(x: Any, shape: tuple[int, int, int], *, fill: float = 0.0, dtype=np.float32) -> np.ndarray:
    a, b, c = int(shape[0]), int(shape[1]), int(shape[2])
    out = np.full((a, b, c), fill, dtype=dtype)
    if a <= 0 or b <= 0 or c <= 0:
        return out
    v = np.asarray(x, dtype=dtype)
    if v.ndim != 3:
        return out
    aa, bb, cc = min(a, v.shape[0]), min(b, v.shape[1]), min(c, v.shape[2])
    if aa > 0 and bb > 0 and cc > 0:
        out[:aa, :bb, :cc] = v[:aa, :bb, :cc]
    return np.nan_to_num(out, nan=fill, posinf=fill, neginf=fill)


def _branch_arrays(d: dict[str, Any], cfg: dict[str, Any]) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Return fixed branch tensors used by GameFormer-level-k training."""
    m_raw = np.asarray(d.get("m_star", np.zeros((1, 0))), dtype=np.float32)
    K_default = int(m_raw.shape[0]) if m_raw.ndim >= 1 and m_raw.shape[0] else int(cfg.get("num_roots", 10))
    L_default = int(m_raw.shape[1]) if m_raw.ndim >= 2 and m_raw.shape[1] else int(cfg.get("num_recovery_options", 12))
    K = _cfg_int(cfg, ("external_baselines", "model", "num_roots"), _cfg_int(cfg, ("num_roots",), K_default))
    L = _cfg_int(cfg, ("external_baselines", "model", "num_options"), _cfg_int(cfg, ("num_recovery_options",), L_default))
    F = _cfg_int(cfg, ("external_baselines", "model", "root_feature_dim"), 18)
    m = _pad_2d(d.get("m_star", np.zeros((0, 0))), (K, L), fill=-1.0, dtype=np.float32)
    root_probs = _pad_1d(d.get("root_probs", np.ones((K,), dtype=np.float32) / max(K, 1)), K, fill=0.0, dtype=np.float32)
    root_valid = _pad_bool_1d(d.get("root_valid", root_probs > 0), K, fill=False)
    root_probs = np.where(root_valid, np.clip(root_probs, 0.0, None), 0.0).astype(np.float32)
    den = float(root_probs.sum())
    if den > 1e-8:
        root_probs /= den
    sig = np.asarray(d.get("root_signature", np.zeros((K, 0))), dtype=np.float32)
    fsig = np.asarray(d.get("root_future_signature", np.zeros((K, 0))), dtype=np.float32)
    if sig.ndim != 2:
        sig = np.zeros((K, 0), dtype=np.float32)
    if fsig.ndim != 2:
        fsig = np.zeros((K, 0), dtype=np.float32)
    sig = _pad_2d(sig, (K, sig.shape[-1] if sig.ndim == 2 else 0), fill=0.0)
    fsig = _pad_2d(fsig, (K, fsig.shape[-1] if fsig.ndim == 2 else 0), fill=0.0)
    raw_feat = np.concatenate([sig, fsig, root_probs[:, None].astype(np.float32), root_valid[:, None].astype(np.float32)], axis=-1)
    root_features = _pad_2d(raw_feat, (K, F), fill=0.0, dtype=np.float32)
    option_valid = _pad_bool_1d(d.get("option_valid", np.ones((L,), dtype=bool)), L, fill=False)
    return m, root_features, root_probs.astype(np.float32), root_valid.astype(bool), option_valid.astype(bool)


def _split_matches_path(path: Path, split: str | set[str]) -> bool:
    splits = {split} if isinstance(split, str) else set(split)
    if "all" in {str(x).lower() for x in splits}:
        return True
    sid = str(scalar_metadata_for_path(path, "split_id", ""))
    return sid in splits


def dataset_label_for_path(path: Path) -> str:
    root = path.parent.parent if path.parent.name == "samples" else path.parent
    return root.name


@lru_cache(maxsize=262144)
def _group_metadata(path_key: str) -> tuple[str, int, int]:
    """Read only scene/time/candidate metadata without expanding large NPZ arrays."""
    path = Path(path_key)
    row = manifest_metadata_for_path(path) or {}
    required = ("scene_id", "time_index", "candidate_index")
    if all(str(row.get(k, "")).strip() != "" for k in required):
        try:
            return str(row["scene_id"]), int(float(row["time_index"])), int(float(row["candidate_index"]))
        except Exception:
            pass
    try:
        with np.load(path, allow_pickle=True) as z:
            scene_raw = np.asarray(z["scene_id"]).item() if "scene_id" in z.files else ""
            if isinstance(scene_raw, bytes):
                scene_raw = scene_raw.decode("utf-8", errors="ignore")
            time_index = int(np.asarray(z["time_index"]).item()) if "time_index" in z.files else 0
            candidate_index = int(np.asarray(z["candidate_index"]).item()) if "candidate_index" in z.files else 0
            return str(scene_raw), time_index, candidate_index
    except Exception:
        return "", 0, 0


def group_sample_paths(dataset: str | Path, split: str | set[str] = "train") -> list[list[Path]]:
    """Group every sample present in the requested dataset split.

    Dataset directories such as ``train_safe`` / ``train_near_contact`` /
    ``train_contact`` are experimental strata, not purity constraints.  The
    external baselines therefore consume the *entire* split exactly as it was
    constructed, including any cross-regime hard examples that are present in
    that directory.  This matches OC-RAP's training-data exposure and avoids an
    asymmetric filtering advantage for external baselines.
    """
    paths = iter_sample_paths_many(dataset)
    grouped: dict[tuple[str, str, int], list[tuple[int, Path]]] = defaultdict(list)
    for p in paths:
        p = Path(p)
        if not _split_matches_path(p, split):
            continue
        scene_id, time_index, candidate_index = _group_metadata(str(p.resolve()))
        grouped[(dataset_label_for_path(p), scene_id, time_index)].append((candidate_index, p))
    out: list[list[Path]] = []
    for _key, group in sorted(grouped.items(), key=lambda kv: (kv[0][0], kv[0][1], kv[0][2])):
        out.append([p for _, p in sorted(group, key=lambda item: (item[0], str(item[1])))])
    return out


def _last_valid_agent_states(agent_history: Any, agent_valid: Any) -> tuple[np.ndarray, np.ndarray]:
    hist = np.asarray(agent_history, dtype=np.float32)
    valid = np.asarray(agent_valid).astype(bool)
    if hist.ndim != 3 or valid.ndim != 2 or hist.shape[:2] != valid.shape:
        return np.zeros((0, 16), dtype=np.float32), np.zeros((0,), dtype=bool)
    _, A, F = hist.shape
    out = np.zeros((A, F), dtype=np.float32)
    out_valid = np.zeros((A,), dtype=bool)
    for a in range(A):
        idx = np.where(valid[:, a])[0]
        if idx.size:
            out[a] = hist[int(idx[-1]), a]
            out_valid[a] = True
    return out, out_valid


def _ego_prefix_xy(d: dict[str, Any]) -> np.ndarray:
    states = np.asarray(d.get("prefix_states", np.zeros((0, 0))), dtype=np.float32)
    if states.ndim == 2 and states.shape[0] > 0 and states.shape[1] >= 2:
        xy = states[:, :2].astype(np.float32)
        if np.isfinite(xy).all():
            return xy
    ego = np.asarray(d.get("ego_state", np.zeros((9,))), dtype=np.float32).reshape(-1)
    x = float(ego[0]) if ego.size > 0 else 0.0
    y = float(ego[1]) if ego.size > 1 else 0.0
    return np.asarray([[x, y], [x, y]], dtype=np.float32)


def _resample_xy(xy: np.ndarray, T: int) -> tuple[np.ndarray, np.ndarray]:
    out = np.zeros((T, 2), dtype=np.float32)
    valid = np.zeros((T,), dtype=bool)
    xy = np.asarray(xy, dtype=np.float32)
    if xy.ndim != 2 or xy.shape[0] == 0 or xy.shape[1] < 2:
        return out, valid
    if xy.shape[0] == T:
        out[:] = xy[:, :2]
        valid[:] = True
        return np.nan_to_num(out), valid
    src = np.linspace(0.0, 1.0, xy.shape[0], dtype=np.float32)
    dst = np.linspace(0.0, 1.0, T, dtype=np.float32)
    out[:, 0] = np.interp(dst, src, xy[:, 0])
    out[:, 1] = np.interp(dst, src, xy[:, 1])
    valid[:] = True
    return np.nan_to_num(out), valid


def _wrap_angle(x: np.ndarray | float) -> np.ndarray | float:
    return (np.asarray(x) + np.pi) % (2.0 * np.pi) - np.pi


def _history_frame(d: dict[str, Any]) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, float, np.ndarray]:
    hist = np.asarray(d.get("agent_history", np.zeros((0, 0, 0))), dtype=np.float32)
    valid = np.asarray(d.get("agent_valid", np.zeros((0, 0))), dtype=bool)
    ego_state = np.asarray(d.get("ego_state", np.zeros((9,))), dtype=np.float32).reshape(-1)
    origin = ego_state[:2].astype(np.float32) if ego_state.size >= 2 else np.zeros(2, dtype=np.float32)
    yaw0 = float(ego_state[4]) if ego_state.size >= 5 else 0.0
    if hist.ndim == 3 and valid.ndim == 2 and hist.shape[:2] == valid.shape and hist.shape[1] > 0:
        idx = np.where(valid[:, 0])[0]
        if idx.size:
            e = hist[int(idx[-1]), 0]
            if e.size >= 2:
                origin = e[:2].astype(np.float32)
            if e.size >= 8:
                yaw0 = float(e[7])
    c, sn = float(np.cos(yaw0)), float(np.sin(yaw0))
    rot = np.asarray([[c, sn], [-sn, c]], dtype=np.float32)
    return hist, valid, ego_state, origin, yaw0, rot


def _history_scene_arrays(
    d: dict[str, Any], cfg: dict[str, Any]
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, float, np.ndarray]:
    """Build scene/time history once for all candidate prefixes in a group."""
    H = _cfg_int(cfg, ("external_baselines", "model", "history_len"), 11)
    A = _cfg_int(cfg, ("external_baselines", "model", "neighbors_to_predict"), 8)
    hist, valid, ego_state, origin, yaw0, rot = _history_frame(d)

    def encode(raw: np.ndarray) -> np.ndarray:
        out = np.zeros((raw.shape[0], GAMEFORMER_STATE_DIM), dtype=np.float32)
        if raw.shape[1] < 2:
            return out
        out[:, :2] = (raw[:, :2] - origin[None, :]) @ rot.T
        out[:, 2] = raw[:, 2] if raw.shape[1] > 2 else 0.0
        if raw.shape[1] >= 5:
            out[:, 3:5] = raw[:, 3:5] @ rot.T
        if raw.shape[1] >= 7:
            out[:, 5:7] = raw[:, 5:7] @ rot.T
        heading = raw[:, 7] if raw.shape[1] > 7 else np.zeros((raw.shape[0],), dtype=np.float32)
        rel_heading = np.asarray(_wrap_angle(heading - yaw0), dtype=np.float32)
        out[:, 7] = rel_heading
        out[:, 8] = np.sin(rel_heading)
        return np.nan_to_num(out)

    ego_hist = np.zeros((H, GAMEFORMER_STATE_DIM), dtype=np.float32)
    neigh_hist = np.zeros((A, H, GAMEFORMER_STATE_DIM), dtype=np.float32)
    neigh_valid = np.zeros((A, H), dtype=bool)
    if hist.ndim == 3 and hist.shape[0] > 0:
        hsel = hist[-H:]
        vsel = valid[-H:] if valid.ndim == 2 and valid.shape[:2] == hist.shape[:2] else np.ones(hsel.shape[:2], dtype=bool)
        if hsel.shape[1] > 0:
            enc = encode(hsel[:, 0])
            ego_hist[-enc.shape[0]:] = enc
        for a in range(min(A, max(hsel.shape[1] - 1, 0))):
            enc = encode(hsel[:, a + 1])
            neigh_hist[a, -enc.shape[0]:] = enc
            neigh_valid[a, -enc.shape[0]:] = vsel[:, a + 1]
    else:
        pseudo = np.zeros((1, 16), dtype=np.float32)
        pseudo[0, :2] = origin
        if ego_state.size >= 4:
            pseudo[0, 3:5] = ego_state[2:4]
        pseudo[0, 7] = yaw0
        ego_hist[:] = encode(pseudo)[0]
    return ego_hist, neigh_hist, neigh_valid.astype(bool), origin, yaw0, rot



def _source_scene_arrays(
    d: dict[str, Any], cfg: dict[str, Any]
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Build candidate-independent scene tensors for source-ported planners.

    The public GameFormer / PlanTF / PLUTO repositories consume actor histories
    and vector-map polygons, not a tensor whose token axis is the executable
    candidate lattice.  OC-RAP stores the same observable information in its
    WOMD-derived NPZs, so this bridge reconstructs a source-like scene once per
    scene/time group and lets the native-style model predict trajectories before
    they are projected back onto the common executable candidate set.

    No future/root/recovery teacher tensor is read here.  The only unavoidable
    dataset adaptation is semantic: WOMD map kinds are kept as compact integer
    categories rather than nuPlan lane-object classes.
    """
    mcfg = ((cfg.get("external_baselines", {}) or {}).get("model", {}) or {})
    H = int(mcfg.get("history_len", 11))
    A = max(1, int(mcfg.get("source_max_agents", int(mcfg.get("neighbors_to_predict", 8)) + 1)))
    M = max(1, int(mcfg.get("source_map_polygons", mcfg.get("num_topology_map", 64))))
    P = max(2, int(mcfg.get("source_map_points", 20)))

    hist, valid, ego_state, origin, yaw0, rot = _history_frame(d)
    agent = np.zeros((A, H, SOURCE_AGENT_STATE_DIM), dtype=np.float32)
    agent_valid = np.zeros((A, H), dtype=bool)

    if hist.ndim == 3 and hist.shape[0] > 0 and hist.shape[1] > 0:
        hsel = hist[-H:]
        if valid.ndim == 2 and valid.shape[:2] == hist.shape[:2]:
            vsel = valid[-H:]
        else:
            vsel = np.ones(hsel.shape[:2], dtype=bool)

        # The public PlanTF feature builder keeps the ego token first and then
        # truncates surrounding actors after sorting them by current distance.
        # Use the same deterministic ordering for all source ports so that the
        # source_max_agents speed cap drops far-away actors rather than an
        # arbitrary WOMD storage suffix.  Ordering depends only on observations.
        actor_order: list[int] = [0]
        nearby: list[tuple[float, int]] = []
        for src_a in range(1, hsel.shape[1]):
            jj = np.where(vsel[:, src_a])[0]
            if jj.size == 0:
                continue
            raw_last = hsel[int(jj[-1]), src_a]
            if raw_last.size < 2 or not np.isfinite(raw_last[:2]).all():
                continue
            nearby.append((float(np.linalg.norm(raw_last[:2] - origin)), int(src_a)))
        nearby.sort(key=lambda x: (x[0], x[1]))
        actor_order.extend(src_a for _dist, src_a in nearby[: max(A - 1, 0)])

        t_off = H - hsel.shape[0]
        for dst_a, src_a in enumerate(actor_order[:A]):
            raw = hsel[:, src_a]
            ok = vsel[:, src_a].astype(bool)
            enc = np.zeros((hsel.shape[0], SOURCE_AGENT_STATE_DIM), dtype=np.float32)
            if raw.shape[1] >= 2:
                enc[:, :2] = (raw[:, :2] - origin[None, :]) @ rot.T
            if raw.shape[1] >= 5:
                enc[:, 2:4] = raw[:, 3:5] @ rot.T
            heading = raw[:, 7] if raw.shape[1] > 7 else np.zeros((raw.shape[0],), dtype=np.float32)
            enc[:, 4] = np.asarray(_wrap_angle(heading - yaw0), dtype=np.float32)
            is_ego = src_a == 0
            enc[:, 5] = raw[:, 10] if raw.shape[1] > 10 else (4.8 if is_ego else 4.5)
            enc[:, 6] = raw[:, 11] if raw.shape[1] > 11 else (2.0 if is_ego else 1.9)
            enc[:, 7] = raw[:, 13] if raw.shape[1] > 13 else 1.0
            enc[:, 8] = ok.astype(np.float32)
            agent[dst_a, t_off:] = np.nan_to_num(enc)
            agent_valid[dst_a, t_off:] = ok

    # PlanTF/PLUTO's first six current-state channels are
    # [x, y, heading, longitudinal speed, longitudinal accel, steering].
    # In the current-ego frame the first three are intentionally zero.  WOMD
    # provides velocity/acceleration but not steering, so steering is the only
    # unavailable source channel and is set to zero rather than inferred from a
    # teacher/future trajectory.
    current = np.zeros((SOURCE_CURRENT_STATE_DIM,), dtype=np.float32)
    if agent_valid[0].any():
        j = int(np.where(agent_valid[0])[0][-1])
        current[3] = float(np.linalg.norm(agent[0, j, 2:4]))
        # OC-RAP raw history keeps ax/ay at columns 5/6.  Project ax onto the
        # current longitudinal axis when available.
        if hist.ndim == 3 and hist.shape[-1] > 5:
            raw_last = hist[-1, 0]
            avec = np.asarray([raw_last[5], raw_last[6] if raw_last.size > 6 else 0.0], dtype=np.float32) @ rot.T
            current[4] = float(avec[0])
    elif ego_state.size >= 7:
        current[3] = float(ego_state[6])

    maps = np.asarray(d.get("map_polylines", np.zeros((0, 0, 0))), dtype=np.float32)
    route = np.asarray(d.get("route", np.zeros((0, 2))), dtype=np.float32)
    map_points = np.zeros((M, P, SOURCE_MAP_POINT_DIM), dtype=np.float32)
    map_point_valid = np.zeros((M, P), dtype=bool)
    map_meta = np.zeros((M, SOURCE_MAP_META_DIM), dtype=np.float32)
    map_center = np.zeros((M, SOURCE_MAP_CENTER_DIM), dtype=np.float32)
    map_valid = np.zeros((M,), dtype=bool)

    rows: list[tuple[float, np.ndarray, np.ndarray]] = []
    if maps.ndim == 3 and maps.shape[0] > 0 and maps.shape[-1] >= 2:
        for mi in range(maps.shape[0]):
            poly = maps[mi]
            if poly.shape[-1] > 9:
                ok = poly[:, 9] > 0.5
            else:
                ok = np.isfinite(poly[:, :2]).all(axis=-1) & (np.abs(poly[:, :2]).sum(axis=-1) > 1.0e-6)
            ok &= np.isfinite(poly[:, :2]).all(axis=-1)
            if int(ok.sum()) < 2:
                continue
            vv = poly[ok]
            center = vv[:, :2].mean(axis=0)
            rows.append((float(np.linalg.norm(center)), vv, center))
    rows.sort(key=lambda z: z[0])

    route_xy = route[:, :2] if route.ndim == 2 and route.shape[0] > 1 else np.zeros((0, 2), dtype=np.float32)
    for i, (_dist0, vv, center) in enumerate(rows[:M]):
        idx = np.linspace(0, len(vv) - 1, min(P, len(vv))).round().astype(int)
        pts = vv[idx]
        q = len(pts)
        xy = pts[:, :2]
        if pts.shape[1] >= 5:
            vec = pts[:, 3:5]
        else:
            vec = np.diff(xy, axis=0, append=xy[-1:])
        small = np.linalg.norm(vec, axis=-1) < 1.0e-6
        if bool(small.any()):
            fallback = np.diff(xy, axis=0, append=xy[-1:])
            vec = np.where(small[:, None], fallback, vec)
        theta = np.arctan2(vec[:, 1], vec[:, 0])
        map_points[i, :q] = np.concatenate(
            [xy - center[None, :], vec, np.cos(theta)[:, None], np.sin(theta)[:, None]], axis=-1
        ).astype(np.float32)
        map_point_valid[i, :q] = True
        seg = xy[-1] - xy[0]
        heading = float(np.arctan2(seg[1], seg[0])) if float(np.linalg.norm(seg)) > 1.0e-6 else 0.0
        map_center[i] = np.asarray([center[0], center[1], heading], dtype=np.float32)
        kind = float(np.median(pts[:, 5])) if pts.shape[1] > 5 else 0.0
        speed = float(np.max(pts[:, 6])) if pts.shape[1] > 6 else 0.0
        route_flag = float(np.max(pts[:, 7])) if pts.shape[1] > 7 else 0.0
        if route_flag <= 0.0 and route_xy.size:
            # WOMD parser does not always populate a route flag.  This uses only
            # the observed planner route and map geometry, so it is deployable.
            route_flag = float(np.min(np.linalg.norm(xy[:, None, :] - route_xy[None, :, :], axis=-1)) < 2.5)
        traffic = float(np.max(pts[:, 8])) if pts.shape[1] > 8 else 0.0
        map_meta[i] = np.asarray([kind, route_flag, traffic, speed], dtype=np.float32)
        map_valid[i] = True

    # Source PDM-Offset uses a 120-pose centerline.  Keep a compact observable
    # centerline tensor available even though the shipped v54 closed-loop hybrid
    # projection deliberately does not train an offset model on short-horizon
    # OC-RAP prefixes (see fidelity audit).
    R = max(2, int(mcfg.get("source_centerline_points", 120)))
    centerline = np.zeros((R, 3), dtype=np.float32)
    if route_xy.shape[0] >= 2:
        ridx = np.linspace(0, route_xy.shape[0] - 1, R).round().astype(int)
        rxy = route_xy[ridx]
        rd = np.diff(rxy, axis=0, append=rxy[-1:])
        rhead = np.arctan2(rd[:, 1], rd[:, 0])
        centerline[:] = np.concatenate([rxy, rhead[:, None]], axis=-1)
    else:
        centerline[:, 0] = np.arange(R, dtype=np.float32)

    return (
        np.nan_to_num(agent), agent_valid, np.nan_to_num(current),
        np.nan_to_num(map_points), map_point_valid, np.nan_to_num(map_meta),
        np.nan_to_num(map_center), map_valid, np.nan_to_num(centerline),
    )

def _prefix_traj_array(
    d: dict[str, Any], cfg: dict[str, Any], origin: np.ndarray, rot: np.ndarray
) -> tuple[np.ndarray, np.ndarray]:
    T = _cfg_int(cfg, ("external_baselines", "model", "future_len"), 20)
    prefix_xy, prefix_valid = _resample_xy(_ego_prefix_xy(d), T)
    prefix_xy = (prefix_xy - origin[None, :]) @ rot.T
    return np.nan_to_num(prefix_xy), prefix_valid.astype(bool)


def _history_arrays(d: dict[str, Any], cfg: dict[str, Any]) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Return deployable GameFormer-style histories in the current ego frame."""
    ego_hist, neigh_hist, neigh_valid, origin, _yaw0, rot = _history_scene_arrays(d, cfg)
    prefix_xy, prefix_valid = _prefix_traj_array(d, cfg, origin, rot)
    return ego_hist, neigh_hist, neigh_valid, prefix_xy, prefix_valid

def _segments_intersect_numpy(line1_start: np.ndarray, line1_end: np.ndarray, line2_start: np.ndarray, line2_end: np.ndarray) -> np.ndarray:
    """NumPy transcription of BeTop ``topo_utils.segments_intersect``."""
    dx1 = line1_end[..., 0] - line1_start[..., 0]
    dy1 = line1_end[..., 1] - line1_start[..., 1]
    dx2 = line2_end[..., 0] - line2_start[..., 0]
    dy2 = line2_end[..., 1] - line2_start[..., 1]
    det = dx1 * dy2 - dx2 * dy1
    good = np.abs(det) > 1.0e-12
    num1 = (line2_start[..., 0] - line1_start[..., 0]) * dy2 - (line2_start[..., 1] - line1_start[..., 1]) * dx2
    num2 = (line2_start[..., 0] - line1_start[..., 0]) * dy1 - (line2_start[..., 1] - line1_start[..., 1]) * dx1
    t1 = np.divide(num1, det, out=np.zeros_like(num1, dtype=float), where=good)
    t2 = np.divide(num2, det, out=np.zeros_like(num2, dtype=float), where=good)
    return good & (t1 >= 0.0) & (t1 <= 1.0) & (t2 >= 0.0) & (t2 <= 1.0)


def _crossing_binary(src_xy: np.ndarray, tgt_xy: np.ndarray, threshold: float = 3.0) -> bool:
    """Exact BeTop behavior-braid indicator on an OC-RAP future proxy.

    ``generate_behavior_braids`` in the official repository swaps x/y, negates
    the new x coordinate, then tests intersections of each trajectory in the
    (transformed-x, normalized-time) plane.  Hence the braid coordinate is the
    negative lateral coordinate and *not* a Euclidean-distance threshold.  The
    target future available in the current serialized OC-RAP dataset is still an
    observation-only constant-velocity extrapolation; that unavoidable label
    source adaptation is documented in provenance rather than hidden here.
    """
    del threshold  # kept only for backward-compatible call sites
    T = min(int(src_xy.shape[0]), int(tgt_xy.shape[0]))
    if T < 2:
        return False
    src = np.asarray(src_xy[:T, :2], dtype=float)
    tgt = np.asarray(tgt_xy[:T, :2], dtype=float)
    finite = np.isfinite(src).all(axis=-1) & np.isfinite(tgt).all(axis=-1)
    traj_t = np.linspace(0.0, 1.0, T, dtype=float)
    # Official source: [...,[0,1]]=[y,x], then x=-x.
    src_xt = np.stack([-src[:, 1], traj_t], axis=-1)
    tgt_xt = np.stack([-tgt[:, 1], traj_t], axis=-1)
    valid_seg = finite[:-1] & finite[1:]
    if not bool(valid_seg.any()):
        return False
    inter = _segments_intersect_numpy(src_xt[:-1], src_xt[1:], tgt_xt[:-1], tgt_xt[1:])
    return bool(np.any(inter & valid_seg))


def _topology_scene_context(d: dict[str, Any], cfg: dict[str, Any]) -> dict[str, Any]:
    """Preselect candidate-independent BeTop actor/map rows once per group.

    All executable candidates in one OC-RAP group share the same current scene.
    v57 rebuilt and resorted the identical actor/map observations for every
    candidate.  This cache contains only observation-time quantities; all
    candidate-dependent braid features/targets are still recomputed exactly.
    """
    Amax = max(_cfg_int(cfg, ("external_baselines", "model", "num_topology_agents"), _cfg_int(cfg, ("max_agents",), 16)), 1)
    Mmax = max(_cfg_int(cfg, ("external_baselines", "model", "num_topology_map"), 64), 1)
    T = _cfg_int(cfg, ("external_baselines", "model", "future_len"), 20)
    ego_xy, _ = _resample_xy(_ego_prefix_xy(d), T)
    e0 = ego_xy[0]

    states, valid = _last_valid_agent_states(d.get("agent_history", np.zeros((0, 0, 0))), d.get("agent_valid", np.zeros((0, 0))))
    actor_rows: list[tuple[float, np.ndarray, np.ndarray, np.ndarray]] = []
    for a in range(1, states.shape[0]):
        if not valid[a] or states.shape[1] < 2:
            continue
        st = states[a]
        p0 = np.asarray([float(st[0]), float(st[1])], dtype=np.float32)
        vel = np.asarray([float(st[3]) if st.size > 3 else 0.0, float(st[4]) if st.size > 4 else 0.0], dtype=np.float32)
        actor_rows.append((float(np.linalg.norm(p0 - e0)), p0, vel, st))
    actor_rows.sort(key=lambda z: z[0])

    maps = np.asarray(d.get("map_polylines", np.zeros((0, 0, 0))), dtype=np.float32)
    if maps.ndim != 3 or maps.shape[0] == 0 or maps.shape[2] < 2:
        route = np.asarray(d.get("route", np.zeros((0, 2))), dtype=np.float32)
        maps = route[None, :, :2] if route.ndim == 2 and route.shape[0] > 1 else np.zeros((0, 0, 2), dtype=np.float32)
    map_rows: list[tuple[float, np.ndarray]] = []
    if maps.ndim == 3:
        for m in range(maps.shape[0]):
            xy = maps[m, :, :2]
            valid_xy = np.isfinite(xy).all(axis=-1) & (np.abs(xy).sum(axis=-1) > 1e-6)
            if int(valid_xy.sum()) < 2:
                continue
            xy = xy[valid_xy]
            center = xy.mean(axis=0)
            map_rows.append((float(np.linalg.norm(center - e0)), xy))
    map_rows.sort(key=lambda z: z[0])
    return {"actor_rows": actor_rows[:Amax], "map_rows": map_rows[:Mmax]}


def _actor_topology_arrays(d: dict[str, Any], cfg: dict[str, Any], scene_context: dict[str, Any] | None = None) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    Amax = _cfg_int(cfg, ("external_baselines", "model", "num_topology_agents"), _cfg_int(cfg, ("max_agents",), 16))
    Amax = max(Amax, 1)
    T = _cfg_int(cfg, ("external_baselines", "model", "future_len"), 20)
    dt = _cfg_float(cfg, ("external_baselines", "model", "topology_dt"), 0.1)
    far = _cfg_float(cfg, ("external_baselines", "model", "topology_far_threshold_m"), 30.0)
    feats = np.zeros((Amax, ACTOR_TOPO_FEATURE_DIM), dtype=np.float32)
    targets = np.zeros((Amax,), dtype=np.float32)
    mask = np.zeros((Amax,), dtype=bool)

    ego_xy, _ = _resample_xy(_ego_prefix_xy(d), T)
    e0 = ego_xy[0]
    eT = ego_xy[-1]
    ego_v = (eT - e0) / max((T - 1) * dt, 1e-3)
    fwd = eT - e0
    fwd_norm = float(np.linalg.norm(fwd))
    if fwd_norm < 1e-3:
        yaw = 0.0
        ego = np.asarray(d.get("ego_state", np.zeros((9,))), dtype=np.float32).reshape(-1)
        if ego.size >= 5:
            yaw = float(ego[4])
        elif ego.size >= 3:
            yaw = float(ego[2])
        fwd = np.asarray([np.cos(yaw), np.sin(yaw)], dtype=np.float32)
        fwd_norm = 1.0
    fwd = fwd / max(fwd_norm, 1e-6)
    left = np.asarray([-fwd[1], fwd[0]], dtype=np.float32)

    if scene_context is not None and "actor_rows" in scene_context:
        rows = scene_context["actor_rows"]
    else:
        states, valid = _last_valid_agent_states(d.get("agent_history", np.zeros((0, 0, 0))), d.get("agent_valid", np.zeros((0, 0))))
        rows = []
        for a in range(1, states.shape[0]):
            if not valid[a] or states.shape[1] < 2:
                continue
            s = states[a]
            p0 = np.asarray([float(s[0]), float(s[1])], dtype=np.float32)
            v = np.asarray([float(s[3]) if s.size > 3 else 0.0, float(s[4]) if s.size > 4 else 0.0], dtype=np.float32)
            d0 = float(np.linalg.norm(p0 - e0))
            rows.append((d0, p0, v, s))
        rows.sort(key=lambda x: x[0])
    ts = np.arange(T, dtype=np.float32)[:, None] * dt
    for i, (d0, p0, v, s) in enumerate(rows[:Amax]):
        agent_xy = p0[None, :] + ts * v[None, :]
        rel0 = p0 - e0
        relT = agent_xy[-1] - eT
        dist = np.linalg.norm(agent_xy - ego_xy, axis=-1)
        min_dist = float(np.min(dist)) if dist.size else d0
        lat0 = float(np.dot(rel0, left))
        lon0 = float(np.dot(rel0, fwd))
        latT = float(np.dot(relT, left))
        lonT = float(np.dot(relT, fwd))
        closing = float(np.dot(v - ego_v, fwd))
        speed = float(np.linalg.norm(v))
        in_range = d0 <= far or min_dist <= far
        feats[i] = np.asarray([
            rel0[0] / 80.0, rel0[1] / 80.0, relT[0] / 80.0, relT[1] / 80.0,
            float(v[0]) / 20.0, float(v[1]) / 20.0, float(ego_v[0]) / 20.0, float(ego_v[1]) / 20.0,
            d0 / 80.0, min_dist / 40.0, lat0 / 20.0, lon0 / 40.0, latT / 20.0, lonT / 40.0,
            closing / 20.0, speed / 20.0,
        ], dtype=np.float32)
        targets[i] = float(in_range and _crossing_binary(ego_xy, agent_xy, threshold=3.0))
        mask[i] = bool(in_range)
    return np.nan_to_num(feats), targets.astype(np.float32), mask


def _map_topology_arrays(d: dict[str, Any], cfg: dict[str, Any], scene_context: dict[str, Any] | None = None) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """BeTop map-braid features/targets with source-exact nearest-polyline labels."""
    Mmax = _cfg_int(cfg, ("external_baselines", "model", "num_topology_map"), 64)
    Mmax = max(Mmax, 1)
    T = _cfg_int(cfg, ("external_baselines", "model", "future_len"), 20)
    ego_xy, ego_valid = _resample_xy(_ego_prefix_xy(d), T)
    e0 = ego_xy[0]
    eT = ego_xy[-1]
    feats = np.zeros((Mmax, MAP_TOPO_FEATURE_DIM), dtype=np.float32)
    targets = np.zeros((Mmax,), dtype=np.float32)
    mask = np.zeros((Mmax,), dtype=bool)
    if scene_context is not None and "map_rows" in scene_context:
        selected = scene_context["map_rows"][:Mmax]
    else:
        maps = np.asarray(d.get("map_polylines", np.zeros((0, 0, 0))), dtype=np.float32)
        if maps.ndim != 3 or maps.shape[0] == 0 or maps.shape[2] < 2:
            route = np.asarray(d.get("route", np.zeros((0, 2))), dtype=np.float32)
            if route.ndim == 2 and route.shape[0] > 1:
                maps = route[None, :, :2]
            else:
                return feats, targets, mask
        rows: list[tuple[float, np.ndarray]] = []
        for m in range(maps.shape[0]):
            xy = maps[m, :, :2]
            valid = np.isfinite(xy).all(axis=-1) & (np.abs(xy).sum(axis=-1) > 1e-6)
            if int(valid.sum()) < 2:
                continue
            xy = xy[valid]
            center = xy.mean(axis=0)
            rows.append((float(np.linalg.norm(center - e0)), xy))
        rows.sort(key=lambda x: x[0])
        selected = rows[:Mmax]
    if not selected:
        return feats, targets, mask

    # First construct features and the per-time distance table.  The official
    # ``generate_map_briads`` chooses exactly the nearest valid polyline at each
    # future step, then marks it if the distance is <3 m.  v57 instead marked
    # every polyline that ever came within 3 m, which can create parallel-lane
    # false positives.
    time_poly_dist = np.full((T, len(selected)), np.inf, dtype=float)
    for i, (d0, xy) in enumerate(selected):
        center = xy.mean(axis=0)
        seg = xy[-1] - xy[0]
        seg_len = float(np.linalg.norm(seg))
        seg_dir = seg / max(seg_len, 1e-6)
        dist = np.linalg.norm(ego_xy[:, None, :] - xy[None, :, :], axis=-1)
        min_dist_t = np.min(dist, axis=1) if dist.size else np.full((T,), np.inf)
        time_poly_dist[:, i] = min_dist_t
        min_dist = float(np.min(min_dist_t)) if min_dist_t.size else 1e6
        nearest = xy[int(np.argmin(np.linalg.norm(xy - eT[None, :], axis=-1)))]
        rel0 = center - e0
        relT = nearest - eT
        feats[i] = np.asarray([
            rel0[0] / 80.0, rel0[1] / 80.0, relT[0] / 80.0, relT[1] / 80.0,
            center[0] / 200.0, center[1] / 200.0, seg_dir[0], seg_dir[1], seg_len / 80.0,
            d0 / 80.0, min_dist / 20.0, float(xy.shape[0]) / 100.0,
            float(np.std(xy[:, 0])) / 80.0, float(np.std(xy[:, 1])) / 80.0,
        ], dtype=np.float32)
        mask[i] = bool(d0 < 100.0 or min_dist < 10.0)

    if len(selected):
        nearest_idx = np.argmin(time_poly_dist, axis=1)
        nearest_dist = time_poly_dist[np.arange(T), nearest_idx]
        for t in range(T):
            if bool(ego_valid[t]) and np.isfinite(nearest_dist[t]) and nearest_dist[t] < 3.0:
                targets[int(nearest_idx[t])] = 1.0
    return np.nan_to_num(feats), targets.astype(np.float32), mask


def _topology_arrays(d: dict[str, Any], cfg: dict[str, Any]) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Backward-compatible alias for old BeTop-lite checkpoints."""
    feats, targets, mask = _actor_topology_arrays(d, cfg)
    return feats, targets.astype(np.int64), mask


def _target_index(samples: list[dict[str, Any]], baseline: str, cfg: dict[str, Any]) -> int:
    """Return the training target without leaking OC-RAP teacher certificates.

    Wayformer, GameFormer and BeTop are trained as architecture-matched
    imitation/planning adapters on the logged nominal candidate.  An old
    teacher-ranked target can still be requested for diagnostics, but requires
    both ``supervision_target=teacher_rank`` and
    ``allow_teacher_supervision=true`` so it cannot be enabled accidentally.
    """
    bcfg = cfg.get("external_baselines", {}) if isinstance(cfg.get("external_baselines", {}), dict) else {}
    feasible = np.asarray([_scalar(d, "feasible", 1.0) > 0.5 for d in samples], dtype=bool)
    nominal = [i for i, d in enumerate(samples) if _scalar(d, "is_nominal", 0.0) > 0.5]
    nominal_idx = int(nominal[0] if nominal else 0)
    mode = str(bcfg.get("supervision_target", "logged_nominal")).lower()
    allow_teacher = bool(bcfg.get("allow_teacher_supervision", False))
    if mode != "teacher_rank" or not allow_teacher:
        # Pure imitation planners must imitate the logged trajectory even when
        # OC-RAP's candidate-level feasibility annotation marks that prefix as
        # undesirable. Falling back to a different "feasible" candidate would
        # silently inject OC-RAP supervision into the external baseline.
        return nominal_idx

    utility = np.asarray([_scalar(d, "utility", 0.0) for d in samples], dtype=np.float32)
    hard = np.asarray([_scalar(d, "hard_violation", 0.0) for d in samples], dtype=np.float32)
    harm = np.asarray([_scalar(d, "harm_proxy", 0.0) for d in samples], dtype=np.float32)
    r_orc = np.asarray([_scalar(d, "r_orc_star", 0.0) for d in samples], dtype=np.float32)
    score = utility - float(bcfg.get("hard_weight", 12.0)) * hard - float(bcfg.get("harm_weight", 2.0)) * harm + float(bcfg.get("oracle_weight", 1.0)) * r_orc
    score = np.where(feasible, score, -1.0e9)
    return int(np.argmax(score)) if score.size else 0


class ExternalGroupDataset(Dataset):
    """Dataset of candidate-prefix sets grouped by scene/time.

    The tensor contract is architecture-aware: GameFormer does not materialize
    BeTop topology tensors, and deployable models do not materialize teacher-only
    root tensors. This removes unused NPZ processing while leaving model inputs
    and optimization objectives unchanged.
    """

    def __init__(self, dataset: str | Path, cfg: dict[str, Any], *, split: str = "train", baseline: str = "route_bc_lite"):
        self.cfg = cfg
        self.baseline = str(baseline)
        self.groups = group_sample_paths(dataset, split=split)
        if not self.groups:
            raise ValueError(f"No grouped samples found in {dataset!s} for split={split!r}")
        first = load_external_sample(self.groups[0][0])
        self.feature_dim = int(sample_to_feature(first, cfg).shape[0])
        bcfg = cfg.get("external_baselines", {}) if isinstance(cfg.get("external_baselines", {}), dict) else {}
        mcfg = bcfg.get("model", {}) if isinstance(bcfg.get("model", {}), dict) else {}
        self.arch = str(mcfg.get("arch", self.baseline)).lower()
        self.implementation = str(mcfg.get("implementation", bcfg.get("implementation", ""))).lower()
        self.max_candidates = int(bcfg.get("max_candidates", max(len(g) for g in self.groups)))
        self.use_teacher_branch_context = use_teacher_branch_context(cfg)
        self.need_history = self.arch in {"gameformer", "gameformer_lite", "gameformer_levelk", "plantf", "plan_tf", "plantf_adapter", "pluto", "pluto_adapter"}
        self.need_prefix_traj = self.need_history or self.arch in {"route_bc_wayformer", "wayformer_bc", "wayformer_scene_bc"}
        self.need_source_scene = self.arch in {"gameformer", "gameformer_lite", "gameformer_levelk", "plantf", "plan_tf", "plantf_adapter", "pluto", "pluto_adapter", "route_bc_wayformer", "wayformer_bc", "wayformer_scene_bc"}
        self.source_port_arch = (
            self.implementation in {"source_port", "source_port_v54", "sourceported_v54"}
            and self.arch in {"gameformer", "gameformer_lite", "gameformer_levelk", "plantf", "plan_tf", "plantf_adapter", "pluto", "pluto_adapter"}
        )
        # Source ports consume source_* actor/map tensors plus prefix_traj.  The
        # older ego_history/neighbor_history bridge is ignored by these models;
        # constructing, repeating across candidates, collating and H2D-copying it
        # was pure overhead.  Keep the legacy tensors for non-source adapters.
        self.materialize_legacy_history = self.need_history and not self.source_port_arch
        # Source-ported GameFormer/PlanTF/PLUTO consume candidate-independent
        # actor/map tensors. Candidate-specific BeTop topology construction is
        # therefore no longer paid for by these safe baselines.
        self.need_topology = self.arch in {"betop", "betop_lite", "betopnet", "betopnet_lite"}

        if self.use_teacher_branch_context:
            m0, rf0, _, _, _ = _branch_arrays(first, cfg)
            self.num_roots = int(m0.shape[0])
            self.num_options = int(m0.shape[1])
            self.root_feature_dim = int(rf0.shape[-1])
        else:
            self.num_roots = _cfg_int(cfg, ("external_baselines", "model", "num_roots"), _cfg_int(cfg, ("num_roots",), 10))
            self.num_options = _cfg_int(cfg, ("external_baselines", "model", "num_options"), _cfg_int(cfg, ("num_recovery_options",), 12))
            self.root_feature_dim = _cfg_int(cfg, ("external_baselines", "model", "root_feature_dim"), 18)

        if self.materialize_legacy_history:
            ego0, neigh0, _, prefix0, _ = _history_arrays(first, cfg)
            self.history_len = int(ego0.shape[0])
            self.neighbors_to_predict = int(neigh0.shape[0])
            self.future_len = int(prefix0.shape[0])
        else:
            # Source ports still persist these geometry values in checkpoints,
            # but do not need the redundant legacy tensors to discover them.
            self.history_len = _cfg_int(cfg, ("external_baselines", "model", "history_len"), 0)
            self.neighbors_to_predict = _cfg_int(cfg, ("external_baselines", "model", "neighbors_to_predict"), 0)
            self.future_len = _cfg_int(cfg, ("external_baselines", "model", "future_len"), 20 if self.need_prefix_traj else 0)

        if self.need_topology:
            at0, _, _ = _actor_topology_arrays(first, cfg)
            mt0, _, _ = _map_topology_arrays(first, cfg)
            self.num_topology_agents = int(at0.shape[0])
            self.actor_topology_feature_dim = int(at0.shape[-1])
            self.num_topology_map = int(mt0.shape[0])
            self.map_topology_feature_dim = int(mt0.shape[-1])
        else:
            self.num_topology_agents = _cfg_int(cfg, ("external_baselines", "model", "num_topology_agents"), 0)
            self.actor_topology_feature_dim = _cfg_int(cfg, ("external_baselines", "model", "actor_topology_feature_dim"), ACTOR_TOPO_FEATURE_DIM)
            self.num_topology_map = _cfg_int(cfg, ("external_baselines", "model", "num_topology_map"), 0)
            self.map_topology_feature_dim = _cfg_int(cfg, ("external_baselines", "model", "map_topology_feature_dim"), MAP_TOPO_FEATURE_DIM)
        self.topology_feature_dim = self.actor_topology_feature_dim

        if self.need_source_scene:
            ss = _source_scene_arrays(first, cfg)
            self.source_max_agents = int(ss[0].shape[0])
            self.source_map_polygons = int(ss[3].shape[0])
            self.source_map_points = int(ss[3].shape[1])
            self.source_centerline_points = int(ss[8].shape[0])
        else:
            self.source_max_agents = _cfg_int(cfg, ("external_baselines", "model", "source_max_agents"), 0)
            self.source_map_polygons = _cfg_int(cfg, ("external_baselines", "model", "source_map_polygons"), 0)
            self.source_map_points = _cfg_int(cfg, ("external_baselines", "model", "source_map_points"), 0)
            self.source_centerline_points = _cfg_int(cfg, ("external_baselines", "model", "source_centerline_points"), 0)

    def __len__(self) -> int:
        return len(self.groups)

    def __getitem__(self, idx: int) -> dict[str, torch.Tensor]:
        paths = self.groups[idx][: self.max_candidates]
        samples = [load_external_sample(p) for p in paths]
        n = len(samples)
        x = np.zeros((self.max_candidates, self.feature_dim), dtype=np.float32)
        mask = np.zeros((self.max_candidates,), dtype=bool)
        utility = np.zeros((self.max_candidates,), dtype=np.float32)
        hard = np.zeros((self.max_candidates,), dtype=np.float32)
        harm = np.zeros((self.max_candidates,), dtype=np.float32)
        r_orc = np.zeros((self.max_candidates,), dtype=np.float32)
        r_dep = np.zeros((self.max_candidates,), dtype=np.float32)
        feasible = np.zeros((self.max_candidates,), dtype=bool)

        out_arrays: dict[str, np.ndarray] = {}
        if self.use_teacher_branch_context:
            out_arrays.update({
                "branch_margins": np.zeros((self.max_candidates, self.num_roots, self.num_options), dtype=np.float32),
                "root_features": np.zeros((self.max_candidates, self.num_roots, self.root_feature_dim), dtype=np.float32),
                "root_probs": np.zeros((self.max_candidates, self.num_roots), dtype=np.float32),
                "root_valid": np.zeros((self.max_candidates, self.num_roots), dtype=bool),
                "option_valid": np.zeros((self.max_candidates, self.num_options), dtype=bool),
            })
        if self.materialize_legacy_history:
            out_arrays.update({
                "ego_history": np.zeros((self.max_candidates, self.history_len, GAMEFORMER_STATE_DIM), dtype=np.float32),
                "neighbor_history": np.zeros((self.max_candidates, self.neighbors_to_predict, self.history_len, GAMEFORMER_STATE_DIM), dtype=np.float32),
                "neighbor_valid": np.zeros((self.max_candidates, self.neighbors_to_predict, self.history_len), dtype=bool),
            })
        if self.need_prefix_traj:
            out_arrays.update({
                "prefix_traj": np.zeros((self.max_candidates, self.future_len, 2), dtype=np.float32),
                "prefix_valid": np.zeros((self.max_candidates, self.future_len), dtype=bool),
            })
        if self.need_topology:
            out_arrays.update({
                "actor_topology_features": np.zeros((self.max_candidates, self.num_topology_agents, self.actor_topology_feature_dim), dtype=np.float32),
                "actor_topology_target": np.zeros((self.max_candidates, self.num_topology_agents), dtype=np.float32),
                "actor_topology_mask": np.zeros((self.max_candidates, self.num_topology_agents), dtype=bool),
                "map_topology_features": np.zeros((self.max_candidates, self.num_topology_map, self.map_topology_feature_dim), dtype=np.float32),
                "map_topology_target": np.zeros((self.max_candidates, self.num_topology_map), dtype=np.float32),
                "map_topology_mask": np.zeros((self.max_candidates, self.num_topology_map), dtype=bool),
            })

        if self.need_source_scene and samples:
            sa, sav, sc, smp, smpv, smeta, smc, smask, scl = _source_scene_arrays(samples[0], self.cfg)
            out_arrays.update({
                "source_agent_history": sa,
                "source_agent_valid": sav,
                "source_current_state": sc,
                "source_map_points": smp,
                "source_map_point_valid": smpv,
                "source_map_meta": smeta,
                "source_map_center": smc,
                "source_map_valid": smask,
                "source_centerline": scl,
            })

        feature_matrix = samples_to_feature_matrix(samples, self.cfg, shared_scene=True)
        if n:
            x[:n] = feature_matrix[:n]
            mask[:n] = True

        shared_history = _history_scene_arrays(samples[0], self.cfg) if self.materialize_legacy_history and samples else None
        shared_topology = _topology_scene_context(samples[0], self.cfg) if self.need_topology and samples else None
        shared_origin = np.zeros((2,), dtype=np.float32); shared_rot = np.eye(2, dtype=np.float32)
        if shared_history is not None:
            shared_eh, shared_nh, shared_nv, shared_origin, _shared_yaw, shared_rot = shared_history
        elif self.need_prefix_traj and samples:
            _hist, _valid, _ego, shared_origin, _yaw, shared_rot = _history_frame(samples[0])

        for i, d in enumerate(samples):
            utility[i] = _scalar(d, "utility", 0.0)
            hard[i] = _scalar(d, "hard_violation", 0.0)
            harm[i] = _scalar(d, "harm_proxy", 0.0)
            r_orc[i] = _scalar(d, "r_orc_star", 0.0)
            r_dep[i] = _scalar(d, "r_dep_star", 0.0)
            feasible[i] = _scalar(d, "feasible", 1.0) > 0.5
            if self.use_teacher_branch_context:
                bm, rf, rp, rv, ov = _branch_arrays(d, self.cfg)
                out_arrays["branch_margins"][i] = bm
                out_arrays["root_features"][i] = rf
                out_arrays["root_probs"][i] = rp
                out_arrays["root_valid"][i] = rv
                out_arrays["option_valid"][i] = ov
            if self.materialize_legacy_history:
                # Candidates in one group share scene/time history.
                out_arrays["ego_history"][i] = shared_eh
                out_arrays["neighbor_history"][i] = shared_nh
                out_arrays["neighbor_valid"][i] = shared_nv
            if self.need_prefix_traj:
                pt, pv = _prefix_traj_array(d, self.cfg, shared_origin, shared_rot)
                out_arrays["prefix_traj"][i] = pt
                out_arrays["prefix_valid"][i] = pv
            if self.need_topology:
                af, at, am = _actor_topology_arrays(d, self.cfg, shared_topology)
                mf, mt, mm = _map_topology_arrays(d, self.cfg, shared_topology)
                out_arrays["actor_topology_features"][i] = af
                out_arrays["actor_topology_target"][i] = at
                out_arrays["actor_topology_mask"][i] = am
                out_arrays["map_topology_features"][i] = mf
                out_arrays["map_topology_target"][i] = mt
                out_arrays["map_topology_mask"][i] = mm

        target = min(_target_index(samples, self.baseline, self.cfg), max(n - 1, 0))
        result = {
            "x": torch.from_numpy(x),
            "mask": torch.from_numpy(mask),
            "target_index": torch.tensor(target, dtype=torch.long),
            "utility": torch.from_numpy(utility),
            "hard": torch.from_numpy(hard),
            "harm": torch.from_numpy(harm),
            "r_orc": torch.from_numpy(r_orc),
            "r_dep": torch.from_numpy(r_dep),
            "feasible": torch.from_numpy(feasible),
        }
        result.update({k: torch.from_numpy(v) for k, v in out_arrays.items()})
        if self.need_topology:
            result.update({
                "topology_features": result["actor_topology_features"],
                "topology_target": result["actor_topology_target"].to(torch.int64),
                "topology_mask": result["actor_topology_mask"],
            })
        return result
